In [3]:
import numpy as np


In [4]:
a=np.arange(5)
print(a)


[0 1 2 3 4]


In [6]:
import tensorflow as tf
print(tf.version())

pos = np.arange(5)[:, None]

AttributeError: module 'tensorflow' has no attribute 'version'

In [7]:
pos = np.arange(5)[:, None]


In [8]:
pe=pos[:, 0::2]
print(pe)


[[0]
 [1]
 [2]
 [3]
 [4]]


In [9]:
a=np.arange(10)
print(a)
print(a[0::2])


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:
b=np.arange(5)
a=np.arange(5)[:,None]
print(a*b)

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
